import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';

export type OrderStatus = 
  | 'pending_payment'
  | 'payment_confirmed'
  | 'purchasing'
  | 'shipped_international'
  | 'in_customs'
  | 'shipped_local'
  | 'delivered'
  | 'cancelled';

export interface Order {
  id: string;
  order_number: string;
  customer_name: string;
  customer_email: string;
  customer_phone: string | null;
  product_url: string;
  product_name: string;
  product_price_usd: number;
  exchange_rate: number;
  service_fee_percentage: number;
  total_kwanza: number;
  status: OrderStatus;
  tracking_number: string | null;
  notes: string | null;
  assigned_operator_id: string | null;
  created_at: string;
  updated_at: string;
}

export interface OrderHistory {
  id: string;
  order_id: string;
  old_status: OrderStatus | null;
  new_status: OrderStatus;
  changed_by: string;
  notes: string | null;
  created_at: string;
}

export interface CreateOrderData {
  customer_name: string;
  customer_email: string;
  customer_phone?: string;
  product_url: string;
  product_name: string;
  product_price_usd: number;
  exchange_rate?: number;
  service_fee_percentage?: number;
  total_kwanza: number;
}

export interface UpdateOrderData {
  status?: OrderStatus;
  tracking_number?: string;
  notes?: string;
  assigned_operator_id?: string;
}

export function useOrders() {
  return useQuery({
    queryKey: ['orders'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as Order[];
    }
  });
}

export function useOrder(id: string) {
  return useQuery({
    queryKey: ['orders', id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select('*')
        .eq('id', id)
        .maybeSingle();
      
      if (error) throw error;
      return data as Order | null;
    },
    enabled: !!id
  });
}

export function useOrderHistory(orderId: string) {
  return useQuery({
    queryKey: ['order-history', orderId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('order_history')
        .select('*')
        .eq('order_id', orderId)
        .order('created_at', { ascending: false });
      
      if (error) throw error;
      return data as OrderHistory[];
    },
    enabled: !!orderId
  });
}

export function useCreateOrder() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async (data: CreateOrderData) => {
      const { data: order, error } = await supabase
        .from('orders')
        .insert({
          ...data,
          order_number: '' // Will be auto-generated by trigger
        })
        .select()
        .single();
      
      if (error) throw error;
      return order as Order;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      toast.success('Pedido criado com sucesso!');
    },
    onError: (error) => {
      toast.error('Erro ao criar pedido: ' + error.message);
    }
  });
}

export function useUpdateOrder() {
  const queryClient = useQueryClient();
  
  return useMutation({
    mutationFn: async ({ id, data }: { id: string; data: UpdateOrderData }) => {
      const { data: order, error } = await supabase
        .from('orders')
        .update(data)
        .eq('id', id)
        .select()
        .single();
      
      if (error) throw error;
      return order as Order;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      queryClient.invalidateQueries({ queryKey: ['orders', variables.id] });
      queryClient.invalidateQueries({ queryKey: ['order-history', variables.id] });
      toast.success('Pedido atualizado com sucesso!');
    },
    onError: (error) => {
      toast.error('Erro ao atualizar pedido: ' + error.message);
    }
  });
}

export function useOrderStats() {
  return useQuery({
    queryKey: ['order-stats'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('orders')
        .select('status, total_kwanza');
      
      if (error) throw error;
      
      const orders = data as { status: OrderStatus; total_kwanza: number }[];
      
      const stats = {
        total: orders.length,
        pending: orders.filter(o => o.status === 'pending_payment').length,
        inProgress: orders.filter(o => 
          ['payment_confirmed', 'purchasing', 'shipped_international', 'in_customs', 'shipped_local'].includes(o.status)
        ).length,
        delivered: orders.filter(o => o.status === 'delivered').length,
        cancelled: orders.filter(o => o.status === 'cancelled').length,
        totalRevenue: orders
          .filter(o => o.status !== 'cancelled')
          .reduce((sum, o) => sum + Number(o.total_kwanza), 0)
      };
      
      return stats;
    }
  });
}
